Student name: Jianwei Su

Date: 06/01/2022

8.1.3


# Create two ndarrays and calculate the inner, outer, dot products, and the correlation matrix.

In [1]:
import numpy as np

In [2]:
#Create two ndarrays
mtr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mtr2=np.array([[5,4,3],[2,5,6],[-5,8,11]])

In [3]:
mtr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
mtr2

array([[ 5,  4,  3],
       [ 2,  5,  6],
       [-5,  8, 11]])

In [5]:
#dot product
mtr1.dot(mtr2)

array([[ -6,  38,  48],
       [  0,  89, 108],
       [  6, 140, 168]])

In [10]:
#Another dot product method
np.dot(mtr1, mtr2)

array([[ -6,  38,  48],
       [  0,  89, 108],
       [  6, 140, 168]])

In [6]:
#dot product
mtr2.dot(mtr1)

array([[ 42,  54,  66],
       [ 64,  77,  90],
       [104, 118, 132]])

In [7]:
#outer
np.outer(mtr1,mtr2)

array([[  5,   4,   3,   2,   5,   6,  -5,   8,  11],
       [ 10,   8,   6,   4,  10,  12, -10,  16,  22],
       [ 15,  12,   9,   6,  15,  18, -15,  24,  33],
       [ 20,  16,  12,   8,  20,  24, -20,  32,  44],
       [ 25,  20,  15,  10,  25,  30, -25,  40,  55],
       [ 30,  24,  18,  12,  30,  36, -30,  48,  66],
       [ 35,  28,  21,  14,  35,  42, -35,  56,  77],
       [ 40,  32,  24,  16,  40,  48, -40,  64,  88],
       [ 45,  36,  27,  18,  45,  54, -45,  72,  99]])

In [8]:
#outer
np.outer(mtr2,mtr1)

array([[  5,  10,  15,  20,  25,  30,  35,  40,  45],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54],
       [ -5, -10, -15, -20, -25, -30, -35, -40, -45],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99]])

In [12]:
#inner
np.inner(mtr1,mtr2)

array([[ 22,  30,  44],
       [ 58,  69,  86],
       [ 94, 108, 128]])

In [13]:
#inner 
np.inner(mtr2, mtr1)

array([[ 22,  58,  94],
       [ 30,  69, 108],
       [ 44,  86, 128]])

In [14]:
#correlation matrix
np.corrcoef(mtr1, mtr2)

array([[ 1.        ,  1.        ,  1.        , -1.        ,  0.96076892,
         0.94063416],
       [ 1.        ,  1.        ,  1.        , -1.        ,  0.96076892,
         0.94063416],
       [ 1.        ,  1.        ,  1.        , -1.        ,  0.96076892,
         0.94063416],
       [-1.        , -1.        , -1.        ,  1.        , -0.96076892,
        -0.94063416],
       [ 0.96076892,  0.96076892,  0.96076892, -0.96076892,  1.        ,
         0.99787083],
       [ 0.94063416,  0.94063416,  0.94063416, -0.94063416,  0.99787083,
         1.        ]])

In [15]:
#correlation matrix
np.corrcoef(mtr2, mtr1)

array([[ 1.        , -0.96076892, -0.94063416, -1.        , -1.        ,
        -1.        ],
       [-0.96076892,  1.        ,  0.99787083,  0.96076892,  0.96076892,
         0.96076892],
       [-0.94063416,  0.99787083,  1.        ,  0.94063416,  0.94063416,
         0.94063416],
       [-1.        ,  0.96076892,  0.94063416,  1.        ,  1.        ,
         1.        ],
       [-1.        ,  0.96076892,  0.94063416,  1.        ,  1.        ,
         1.        ],
       [-1.        ,  0.96076892,  0.94063416,  1.        ,  1.        ,
         1.        ]])