Student name: Jianwei Su

Date: 06/01/2022

8.1.4

# Create two 5x5 matrices of numbers:
# a. Multiply both matrices together.
# b. Compute the eigenvalues of the matrices.
# c. Calculate the correlation matrix for each of the two matrices.

In [1]:
import numpy as np

# Set Seed:
np.random.seed(2)
arr1=np.random.randint(1,1000,25)
arr2=np.random.randint(1,1000,25)

In [2]:
print('Length of array 1:', len(arr1))
print('Length of array 2:', len(arr2))

Length of array 1: 25
Length of array 2: 25


# Create two 5x5 matrices of numbers

In [3]:
mtr1=np.resize(arr1,(5,5))
mtr1

array([[169, 528, 494, 585, 535],
       [300, 467,  76, 361, 264],
       [675, 434, 608, 588, 726],
       [ 48, 832, 288, 731, 405],
       [125, 629, 806, 680, 196]])

In [4]:
mtr2=np.resize(arr2,(5,5))
mtr2

array([[103, 773, 939, 876,  52],
       [360, 551, 546, 571, 893],
       [256, 324, 326,  89, 709],
       [303, 455, 352, 212, 122],
       [ 32, 451, 593, 565, 239]])

# Multiply both matrices together

In [13]:
np.matmul(mtr1, mtr2)

array([[ 528326, 1089081, 1131198,  919793, 1029773],
       [ 336307,  797160,  845082,  761913,  593653],
       [ 582809, 1552867, 1706491, 1428072, 1098984],
       [ 612645, 1104108, 1090709,  926549, 1135641],
       [ 657963, 1102144, 1079153,  795293, 1269455]])

In [14]:
np.matmul(mtr2, mtr1)

array([[ 931680, 1584441,  974742, 1567156, 1305863],
       [ 733723, 1721130, 1435890, 1755200, 1140743],
       [ 453411,  947969,  946382, 1005591,  634181],
       [ 450733,  778359,  557666,  786418,  647549],
       [ 597978, 1105286,  765982, 1105750,  842371]])

# Compute the eigenvalues of the matrices

In [7]:
#mtr1's eigenvalue
np.linalg.eig(mtr1)

(array([2239.73647352 +0.j        , -294.3677312 +73.97514568j,
        -294.3677312 -73.97514568j,   28.36834695 +0.j        ,
         491.63064192 +0.j        ]),
 array([[-0.44140864+0.j        , -0.37299496-0.15131754j,
         -0.37299496+0.15131754j, -0.01188676+0.j        ,
          0.19766963+0.j        ],
        [-0.25131132+0.j        , -0.02689803+0.10564652j,
         -0.02689803-0.10564652j, -0.53072669+0.j        ,
         -0.24523282+0.j        ],
        [-0.60210177+0.j        , -0.24946118+0.12606341j,
         -0.24946118-0.12606341j, -0.23340595+0.j        ,
          0.72384618+0.j        ],
        [-0.3945551 +0.j        , -0.20887232-0.12911688j,
         -0.20887232+0.12911688j,  0.80326669+0.j        ,
         -0.54290917+0.j        ],
        [-0.47307586+0.j        ,  0.82925954+0.j        ,
          0.82925954-0.j        , -0.13591238+0.j        ,
          0.28650292+0.j        ]]))

In [8]:
#mtr2's eigenvalue
np.linalg.eig(mtr2)

(array([2082.27368434, -656.99124516, -158.67007947,   18.28777568,
         146.09986461]),
 array([[ 0.54662836,  0.77109465,  0.46821649, -0.42799017, -0.26287459],
        [ 0.58545978, -0.35515302, -0.74810737,  0.68877652, -0.35861817],
        [ 0.35085666, -0.36214784,  0.05131917, -0.57712279,  0.73569201],
        [ 0.32076249,  0.0097693 ,  0.46052992,  0.04722044, -0.49303841],
        [ 0.36393037,  0.38475041,  0.07992008,  0.08432582,  0.13401623]]))

# Calculate the correlation matrix for each of the two matrices

In [ ]:
np.corrcoef(mtr1, mtr2)