Student name: Jianwei Su

Date: 06/01/2022

8.1.6

In this exercise, we will create a matrix of random numbers that have a predefined correlation. 
In practice, this is really useful when running Monte Carlo simulations over data that has a 
known correlation. For example, if we know a set of underlying Stock prices are correlated and 
we wish to simulate how a portfolio of their Option prices react: We can price each Option using 
a Monte Carlo simulation individually; however, doing so individually will not give us insight into 
the portfolio value. Instead, we can create an array of random, correlated Stock prices. There 
are two ways to do this (you should attempt both), with the following steps:
a. Pick 10 stocks from any stock exchange and get their last 10 closing prices – put these 
into an ndarray, and calculate the covariance matrix.
b. Use numpy.random’s multivariate_normal to create a correlated array of random 
numbers, based on the above covariance matrix. 
c. Use np.random’s standard_normal function to create an array of uncorrelated random 
numbers. Use the following formula to create a correlated array of random numbers:
L = linalg.cholesky(covarianceMatrix) 
corr = DotProduct(L, uncorr)
Note that in practice, for options pricing Monte Carlo simulations, we’d use a lognormal 
distribution, but for simplicity here, we use a normal distribution.

In [1]:
import numpy as np
import yfinance as yf

# Pick 10 stocks from any stock exchange and get their last 10 closing prices – put these into an ndarray, and calculate the covariance matrix

In [2]:
#1.UVXY
#I will use the first one to show more details. 
UVXY=yf.Ticker('UVXY')

#It's to access the history data 
UVXY_data = UVXY.history(period="max")

#This is to show the last ten days' data
UVXY_data.tail(10)

Open       High     Low  Close     Volume  Dividends  \
Date                                                                    
2022-05-18  14.970000  17.820000  14.850  17.65   90002000          0   
2022-05-19  18.129999  18.309999  15.880  15.98   90157500          0   
2022-05-20  15.220000  17.840000  15.110  16.01  108761000          0   
2022-05-23  15.610000  16.420000  15.300  15.74   59639700          0   
2022-05-24  16.129999  16.900000  15.640  15.75   79037700          0   
2022-05-25  16.209999  16.230000  15.040  15.28   49831900          0   
2022-05-26  15.070000  15.160000  14.760  15.09   40465900          0   
2022-05-27  14.530000  14.710000  14.150  14.21   37490100          0   
2022-05-31  14.620000  15.100000  13.710  13.84   51793600          0   
2022-06-01  13.570000  14.770000  13.365  13.69   60769717          0   

            Stock Splits  
Date                      
2022-05-18           0.0  
2022-05-19           0.0  
2022-05-20           0.0  
2022-05-23           0.0  
2022-05-24           0.0  
2022-05-25           0.0  
2022-05-26           0.0  
2022-05-27           0.0  
2022-05-31           0.0  
2022-06-01           0.0

In [3]:
#Get its last ten days' closing prices
UVXY_data['Close'][-10:]

Date
2022-05-18    17.65
2022-05-19    15.98
2022-05-20    16.01
2022-05-23    15.74
2022-05-24    15.75
2022-05-25    15.28
2022-05-26    15.09
2022-05-27    14.21
2022-05-31    13.84
2022-06-01    13.69
Name: Close, dtype: float64

In [4]:
#Another method to get its last ten days' closing prices
UVXY_data.Close[-10:]

Date
2022-05-18    17.65
2022-05-19    15.98
2022-05-20    16.01
2022-05-23    15.74
2022-05-24    15.75
2022-05-25    15.28
2022-05-26    15.09
2022-05-27    14.21
2022-05-31    13.84
2022-06-01    13.69
Name: Close, dtype: float64

In [5]:
# The 2nd stock to the 10th stock I picked

# no.2
IEFA=yf.Ticker('IEFA')
IEFA_data = IEFA.history(period="max")

# no.3
USHY=yf.Ticker('USHY')
USHY_data = USHY.history(period="max")

# no.4
MTUM=yf.Ticker('MTUM')
MTUM_data = MTUM.history(period="max")

# no.5
VIXY=yf.Ticker('VIXY')
VIXY_data = VIXY.history(period="max")

# no.6
ARKG=yf.Ticker('ARKG')
ARKG_data = ARKG.history(period="max")

# no.7
ITB=yf.Ticker('ITB')
ITB_data = ITB.history(period="max")

# no.8
USMV=yf.Ticker('USMV')
USMV_data = USMV.history(period="max")

# no.9
SVXY=yf.Ticker('SVXY')
SVXY_data = SVXY.history(period="max")

# no.10
INDA=yf.Ticker('INDA')
INDA_data = INDA.history(period="max")



# Get 10 last close prices of 10 stocks
last_close_Price = np.array([UVXY_data['Close'][-10:], 
                             IEFA_data['Close'][-10:], 
                             USHY_data['Close'][-10:], 
                             MTUM_data['Close'][-10:], 
                             VIXY_data['Close'][-10:], 
                             ARKG_data['Close'][-10:], 
                             ITB_data['Close'][-10:], 
                             USMV_data['Close'][-10:], 
                             SVXY_data['Close'][-10:], 
                             INDA_data['Close'][-10:]])

In [6]:
cov_matrix=np.cov(last_close_Price)
cov_matrix

array([[ 1.42618206, -1.13788132, -0.7082918 , -4.3467152 ,  1.16493524,
        -0.23031303, -1.95045976, -1.49994058, -1.42475051, -0.33545331],
       [-1.13788132,  1.1903584 ,  0.67826917,  4.03810387, -0.93172357,
         0.30311396,  1.70409312,  1.53741728,  1.1234054 ,  0.2952091 ],
       [-0.7082918 ,  0.67826917,  0.46748502,  2.69796121, -0.58336272,
         0.14376262,  1.24732551,  0.97022646,  0.71026487,  0.151105  ],
       [-4.3467152 ,  4.03810387,  2.69796121, 17.78985993, -3.60601271,
         1.21965682,  8.11920709,  5.8544479 ,  4.45986097,  1.10958758],
       [ 1.16493524, -0.93172357, -0.58336272, -3.60601271,  0.95272848,
        -0.19206205, -1.62062433, -1.23400287, -1.16584155, -0.2748044 ],
       [-0.23031303,  0.30311396,  0.14376262,  1.21965682, -0.19206205,
         0.70371183,  0.7339851 ,  0.29076492,  0.21457549,  0.10233253],
       [-1.95045976,  1.70409312,  1.24732551,  8.11920709, -1.62062433,
         0.7339851 ,  4.09094354,  2.51778896

In [7]:
print('The size of covariance matrix:', cov_matrix.size)

The size of covariance matrix: 100


# Use numpy.random’s multivariate_normal to create a correlated array of random numbers, based on the above covariance matrix. 


In [8]:
Mean = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

correlated_array = np.random.multivariate_normal(Mean, cov_matrix, size=10)
correlated_array

array([[ 7.09723723e-01, -1.46365305e+00, -8.90907729e-01,
        -6.82275991e+00,  6.26739727e-01, -8.74251794e-01,
        -3.00490747e+00, -2.21481899e+00, -7.60244413e-01,
        -3.49151562e-01],
       [ 1.34576465e+00, -4.62960611e-01, -4.84799470e-01,
        -5.03259732e+00,  1.14068343e+00, -1.71046620e-01,
        -2.86413919e+00, -9.01271185e-01, -1.50244679e+00,
        -3.42680390e-01],
       [-1.18355620e+00,  8.53384051e-01,  4.42965306e-01,
         4.45528302e+00, -9.82965980e-01,  6.17259258e-01,
         2.02443698e+00,  1.19084317e+00,  1.28536213e+00,
         4.12274546e-01],
       [ 2.73164792e+00, -1.89878754e+00, -1.35871952e+00,
        -7.88236716e+00,  2.21380447e+00, -6.53640932e-01,
        -3.56386978e+00, -2.85018188e+00, -2.74798013e+00,
        -4.50019661e-01],
       [ 1.50822847e+00, -1.69461798e+00, -7.58552113e-01,
        -5.76545437e+00,  1.22746083e+00, -6.23300484e-01,
        -2.54372689e+00, -2.14867022e+00, -1.57493090e+00,
        -6.

# Use np.random’s standard_normal function to create an array of uncorrelated random numbers. Use the following formula to create a correlated array of random numbers:
# L = linalg.cholesky(covarianceMatrix) 
# corr = DotProduct(L, uncorr)

In [9]:
# Cholesky decomposition
# L = linalg.cholesky(covarianceMatrix)
L = np.linalg.cholesky(cov_matrix) 
L

array([[ 1.19422865e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-9.52816969e-01,  5.31505618e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-5.93095634e-01,  2.12900082e-01,  2.65322712e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-3.63976799e+00,  1.07255906e+00,  1.17171573e+00,
         1.42079141e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 9.75470854e-01, -4.28667213e-03, -1.47088283e-02,
        -2.37141370e-02,  1.96979635e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.

In [10]:
#Use np.random’s standard_normal function to create an array of uncorrelated random numbers.
uncorr_nums = np.random.standard_normal(100)
uncorr_nums.size

100

In [11]:
uncorr=np.resize(uncorr_nums,(10,10))
uncorr

array([[ 0.02945711, -0.59438279, -1.05018536,  0.31432908, -0.35632929,
         1.09204734,  0.84208921, -0.88478498,  0.26648712, -0.35715624],
       [ 0.90728694, -1.49917192, -0.01710536, -1.20243428, -0.85062306,
         0.82408351,  1.31724519, -0.28640613, -1.36710172,  1.2049224 ],
       [ 0.38961187,  0.14887588,  1.36210801,  0.63958691, -1.80452171,
        -0.11868498, -1.40908927,  0.2324928 ,  1.32223226,  0.37439511],
       [-0.22376471,  1.8257713 ,  0.80424643,  0.13060502,  1.07010856,
         0.5219224 ,  0.54583841, -1.31443021,  0.89898484,  1.64018267],
       [-1.51038752,  0.99820812, -0.42977474, -1.12344578, -1.74317657,
         0.99486343,  1.8073703 ,  0.05399046, -0.40856184,  1.37661283],
       [-1.00902408, -1.37988385,  0.15409926,  0.19411119,  0.12207408,
         0.07039834,  0.73029419, -1.19980575,  1.64030177,  1.5687921 ],
       [-1.78888253,  1.92890967, -0.12758623,  0.30150906, -1.05810712,
         0.58383898,  1.51272967,  0.30904162

In [12]:
#corr = DotProduct(L, uncorr)
corr=L.dot(uncorr)
corr

array([[ 3.51785245e-02, -7.09828958e-01, -1.25416144e+00,
         3.75380789e-01, -4.25538647e-01,  1.30415421e+00,
         1.00564706e+00, -1.05663557e+00,  3.18246551e-01,
        -4.26526212e-01],
       [ 4.54160870e-01, -2.30480286e-01,  9.91542833e-01,
        -9.38598656e-01, -1.12594342e-01, -6.02516215e-01,
        -1.02233667e-01,  6.90811681e-01, -9.80535695e-01,
         9.80727551e-01],
       [ 2.79063457e-01,  7.28521685e-02,  9.80616810e-01,
        -2.72728628e-01, -4.48540966e-01, -5.03730879e-01,
        -5.92861210e-01,  5.25471844e-01, -9.82901666e-02,
         5.67691411e-01],
       [ 1.00449315e+00,  3.32394543e+00,  6.54275434e+00,
        -1.49879016e+00, -2.09372951e-01, -2.48844289e+00,
        -2.52771563e+00,  1.31810891e+00,  3.90301652e-01,
         5.36135836e+00],
       [-5.33059474e-03, -5.99200346e-01, -1.07192459e+00,
         2.77138942e-01, -3.77113825e-01,  1.07069333e+00,
         8.59170361e-01, -8.33039852e-01,  2.16995761e-01,
        -3.